### ISSUE TITLE
No Invoice Void Functionality Available. 

### ISSUE THREAD

**Issue by y471n** [mcohen01/node-quickbooks#105]
Hi, I was going through the quickbooks documentation and found out the invoice void feature which seems to be lacking in the current library.

**Comment by riteshjagga** [comment]
+1. Need this method too. Can this be confirmed if it is possible by any of the available methods.

**Comment by ljorgensen** [comment]
You should be able to do this using the updateInvoice method. Set the fields as described in https://developer.intuit.com/hub/blog/2016/04/06/voiding-invoice-objects. I.e. set Deposit to 0, PrivateNote to Voided, LinkedTxn to [], Amount to 0, TotalAmt to 0, and Balance to 0.

**Comment by nthornton2010** [comment]
Why was this closed? @ljorgensen's suggestion is just a band-aid. A permanent solution would be to add support for the void invoice API call which externally works nearly the same way as delete. The only difference is that operation=delete needs to be operation=void in the url of the request.

+1 to needing this too... Real support for it, not clearing everything out manually.

**Comment by mcohen01** [comment]
@nthornton2010 pull requests welcome...

**Comment by ljorgensen** [comment]
My suggestion was based on Intuit's advice at the time. You can refer to https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/invoice#void-an-invoice for their current API.
