### ISSUE TITLE
Document refreshAccessToken

### ISSUE THREAD

**Issue by mLuby** [mcohen01/node-quickbooks#111]
Should be listed in instance method list, especially the fact that the callback signature is non-standard `(error, response) => {}` but `response` can be `{error: "error message"}`

Happy to PR, but I'd like to know more about possible errors if anyone has info on that.

**Comment by mLuby** [comment]
@mcohen01 would you welcome a PR to fix this?

**Comment by kruegernet** [comment]
Lame
