### ISSUE TITLE
Ability to revoke current token

### ISSUE THREAD

**Issue by opedromiranda** [mcohen01/node-quickbooks#114]
It seems that currently there is no method to revoke the given access tokens.

Info on the way it works can be seen here: https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#revoking-access

Possible solution based off the current `refreshAccessToken` method.
```javascript
QuickBooks.prototype.revokeAccessToken = function(callback) {
  var auth = (new Buffer(this.consumerKey + ':' + this.consumerSecret).toString('base64'));

  var postBody = {
      url: 'https://developer.api.intuit.com/v2/oauth2/tokens/revoke',
      headers: {
          Accept: 'application/json',
          'Content-Type': 'application/x-www-form-urlencoded',
          Authorization: 'Basic ' + auth,
      },
      form: {
          token: this.refreshToken
      }
  };

  request.post(postBody, function (e, r) {
      if (!e) {
        this.refreshToken = null;
        this.token = null;
      }
      callback(e);
  });
};```

**Comment by ljorgensen** [comment]
Check out my PR #103, opened in April. The revoke url in prod is different from the url in dev. Also, it’s possible to use either the refreshToken or the OAuth token.

**Comment by ljorgensen** [comment]
You might also want PR #104.

**Comment by mcohen01** [comment]
PR's merged
