### ISSUE TITLE
Obtaining response headers after request error

### ISSUE THREAD

**Issue by opedromiranda** [mcohen01/node-quickbooks#137]
It would be good to have access to the response object (more specifically, in my case, response headers like `intuit_tid`) when we get an error after some faulty request.

Looking at the `module.request`, I'm not exactly sure what would be the right way of doing this. Currently the callback is called with an error like this: 
```javascript
if (callback) {
      if (err ||
          res.statusCode >= 300 ||
          (_.isObject(body) && body.Fault && body.Fault.Error && body.Fault.Error.length) ||
          (_.isString(body) && !_.isEmpty(body) && body.indexOf('<') === 0)) {
        callback(err || body, body)
      } else {
        callback(null, body)
      }
}
```

Maybe something like `callback(err, { body, headers } )` would be good, but it would imply some refactoring.

I'd like to hear your thoughts on this! :)

**Comment by mcohen01** [comment]
`callback(..., body, res)` is backward compatible, no?

**Comment by mcohen01** [comment]
https://github.com/mcohen01/node-quickbooks/pull/138 ?

**Comment by mcohen01** [comment]
`2.0.32` is on npm

**Comment by scole954387** [comment]
> This appears to only be passed to the internal `request` method. The original callback (e.g. `findCustomers`, etc) is only passed `err, data`. Am I misunderstanding how to implement, or is there a way the raw response can be made available to all methods? For my use case, I'm trying to log `intuit_tid` in production.

Did you figure out how to access intuit_tid for logging?  Thanks!

**Comment by scole954387** [comment]
> > Did you figure out how to access intuit_tid for logging? Thanks!
> 
> I was not. IIRC I needed this to debug some occasional API/oauth connection problems, but I've since gotten those worked out.

I figured it out.  This worked for me but I might be using a different version than you.  Hope it helps.

`qbo.createAccount(body, function (err, account, res) {
        console.log("res", res.headers); 

}`

**Comment by scole954387** [comment]
> > Did you figure out how to access intuit_tid for logging? Thanks!
> 
> I was not. IIRC I needed this to debug some occasional API/oauth connection problems, but I've since gotten those worked out.

I figured it out.  This worked for me but I might be using a different version than you.  Hope it helps.

`qbo.createAccount(body, function (err, account, res) {
        console.log("res", res.headers); 

}`
