### ISSUE TITLE
refreshToken arg in QuickBooks constructor

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [mcohen01/node-quickbooks#151]
Looks like [refreshToken argument](https://www.npmjs.com/package/node-quickbooks#public-api) does nothing and can be omitted.

a) I have tried to make a call with expired accessToken and valid refreshToken, thinking that it might refresh and get new accessToken in the background if specified accessToken is expired. However, call was rejected `Token expired: ...`
b) Constructed QuickBooks instance without passing refreshToken and it works.

Any idea about the usage of refreshToken ?
Documentation does not point out any details about this argument.

**Comment by mcohen01** [comment]
https://github.com/mcohen01/node-quickbooks/blob/master/index.js#L141
