### ISSUE TITLE
Add query params support to getReports

### ISSUE THREAD

**Issue by naorpeled** [mcohen01/node-quickbooks#184]
Hey :)

Could you add query params support to the getReports method?
I need to fetch reports for specific dates, it would help me a lot.

Thanks in advance!

**Comment by yashsway** [comment]
Just checking in here - did you find a solution to this? was this implemented somehow?

**Comment by naorpeled** [comment]
> Just checking in here - did you find a solution to this? was this implemented somehow?

Nope,
we ended up making our own QB client,
might open source it one day
