### ISSUE TITLE
Connect Button doesn't work

### ISSUE THREAD

**Issue by cb7754** [mcohen01/node-quickbooks#199]
HI, when I click the connect button (I already code my Client Id and my Cliente Security) the app send me to this page: https://quickbooks.intuit.com/learn-support/en-us/do-more-with-quickbooks/quickbooks-advanced-multi-user-access-to-third-party-apps/00/329767. , instead the login page.

**Comment by cb7754** [comment]
No, unfortunately I have no solution yet,  and Quickbooks support didn't answer my question.

**Comment by damiankrzyz** [comment]
I just managed to work this out. The example is using version 1.0 of the oauth.
You can try and copy the code from oauth2example > app.js to enable version 2.0
