### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by stellar-scottreed** [mcohen01/node-quickbooks#200]
Many new commits to master since last version available on NPM ([2.0.39](https://www.npmjs.com/package/node-quickbooks/v/2.0.39))

Perhaps a new minor version could be published to npm?

I suggest this PR should be merged in before new version is published: https://github.com/mcohen01/node-quickbooks/pull/196/files

Thanks!

**Comment by mcohen01** [comment]
`2.0.41` is on npm
