### ISSUE TITLE
Re-creating transactions

### ISSUE THREAD

**Issue by nshtech** [mcohen01/node-quickbooks#21]
I was able to delete sales receipts using the method. But I found that I am not able to re-create those sales receipts.

I wasn't able to accomplish that through established Quickbooks integrations either. Both Shopify-to-QB sync and Paypal-to-QB sync apps provided by those respective platforms are not able to re-create deleted sales receipts.

Is this something that is not possible to do?

**Comment by mcohen01** [comment]
Sorry, I don't know offhand. Maybe you can try changing the status. Were you getting an error when trying to recreate?

**Comment by nshtech** [comment]
No, I was being returned a null value for error in the callback. I'm not sure what you mean by status? Thanks for the reply.

**Comment by mhong19414** [comment]
Actually now I am getting an error. It goes:

{ Fault: 
   { Error: 
      [ { Message: 'Object Not Found',
          Detail: 'Object Not Found : Another user has deleted this transaction.',
          code: '610',
          element: '' } ],
     type: 'ValidationFault' },
  time: '2015-10-06T08:25:43.233-07:00' }

**Comment by mcohen01** [comment]
Yeah, that is correct I think. Once the transaction is deleted it's effectively uneditable after that.
