### ISSUE TITLE
Not able to authenticate from saved credentials

### ISSUE THREAD

**Issue by camikazegreen** [mcohen01/node-quickbooks#23]
I am able to access the API just fine during the initial authentication, but after I save the tokens in my database and try to access the API directly without going through the authentication I always get a 401 error code 3200.

Here is my code:
```
qbo = new QB(
			consumerKey,
			consumerSecret,
			results[0].oauth_token,
			results[0].oauth_token_secret,
			results[0].realmId,
			false,//sandbox
			true);//debugging

		qbo.findVendors(" where GivenName = 'Alison'",function(err,vendors){
			if(err){
			console.log(err);
		}
			console.log(vendors);
			return res.view('quickbooks/manage',{vendors:vendors})
		})
```

**Comment by mcohen01** [comment]
I assume there's some issue with writing to or reading the tokens from the db and passing them into a new Quickbooks object...

**Comment by noyg** [comment]
@camikazegreen can you shed some light on what was the origin of the error for you?
