### ISSUE TITLE
Credit card authorization charge error 

### ISSUE THREAD

**Issue by jayanthelango** [mcohen01/node-quickbooks#24]
HI,
     i used below code to receive token
var chargedn = { "card": { "expYear": "2017", "expMonth": "03", "address": { "region": "NJ", "postalCode": "07079", "streetAddress": "350 Mountain View Dr.", "country": "US", "city": "South Orange" }, "name": "Pye's Cakes", "cvc": "123", "number": "4111111111111111" } } qbo.cardToken(chargedn, function(err, cardToken) { token = cardToken.value console.log(token); console.log(err); }); 

Next step i used below code to authorize the token 
 qbo.charge({ "amount": "80.00", "currency": "USD", "capture": "false", "token": "Xq83uiLpMtTPjXjDM/XO7jlsYPs=", }, function(err, cardToken) {	console.log(cardToken); console.log(err); }); 
 Its throwing 401 error with response body as undefined.  I tried by adding and removing  authorization on header still i am getting the same 401 error.

**Comment by mcohen01** [comment]
401 indicates an authorization problem. I would suggest double checking your keys match your environment.
