### ISSUE TITLE
Using "count" in an array or passing in a string doesn't work for me

### ISSUE THREAD

**Issue by zigrivers** [mcohen01/node-quickbooks#26]
I'm a junior developer, so forgive me if this is something I'm doing wrong, or not understanding about the api.

I've been trying to create a function that will get me a count of records with a where clause. I've tried to do this via an array with "count" as the first object in the array, and I've tried to pass in a string query. The string query fails on me (maybe I misunderstood the api and I can't pass strings like I've done in my example code below?). The array query works, but it doesn't return a count - instead it does a SELECT * with my WHERE clause and I get back all of the expenses. Here's my code:

```javascript
function getExpenseCountFor( range, quickBooksObject ) {
            let query = [
                {
                    count : true
                },
                {
                    field    : 'TxnDate', //transaction date
                    value    : range.start_date, //start date
                    operator : '>='
                },
                {
                    field    : 'TxnDate',
                    value    : range.end_date,
                    operator : '<='
                }
            ];
            let queryString = 'SELECT COUNT(*) FROM Purchase WHERE TxnDate > \'2015-10-01\' AND TxnDate <= CURRENT_DATE';

            return new Promise(function( resolve, reject ) {
                quickBooksObject.findPurchases(query, ( error, expenseCount ) => {
                    if ( error ) {
                        reject(error);
                    }
                    resolve(expenseCount);
                });
            });
        }
```

Any recommendations or guidance if I'm doing something wrong?

**Comment by mcohen01** [comment]
Sorry, this was a bug. Your array based query should work now in 1.0.25.

**Comment by mcohen01** [comment]
String based queries should work too, but they begin with the where clause:

`"WHERE TxnDate > '2015-10-01' AND TxnDate <= CURRENT_DATE"`

**Comment by zigrivers** [comment]
Thank you! I’ve been banging my head on this one. I’ll update when I get back to my office and give it a try.

Thanks,

Ken Allred
Direct:   385.351.6600
Mobile:  801.580.9933

[Twitter_round]<https://twitter.com/Zigrivers> [LinkedIn_round] <http://www.linkedin.com/in/kenallred>  [Google Plus_round] <https://plus.google.com/+PrimaryIntel-TruVoice/posts>
