### ISSUE TITLE
Wildcard Queries with LIKE

### ISSUE THREAD

**Issue by shizy** [mcohen01/node-quickbooks#30]
When querying using LIKE, I found that any wildcards (%) used need to be escaped to be url encoded correctly. However, if using multiple wildcards, the second wildcard is not converted to %25, even when escaped.

Ex:
```
{ field: 'Name', value: '\%foobar\%', operator: 'LIKE' }
```
Result from the request string: 
```
...WHERE%20Name%20LIKE%20%27%25foobar%%27
```

Instead, of %25 after 'foobar', the second wildcard merely appears as an additional '%'. Perhaps a missing 'global' flag on a regex replace?

Thanks!

**Comment by mcohen01** [comment]
1.0.27 is available
