### ISSUE TITLE
Query based on nested properties

### ISSUE THREAD

**Issue by bsbechtel** [mcohen01/node-quickbooks#35]
How can I query nested properties in an object? For example, I want to find:

              qbo.findItems({
                Name: name,
                ParentRef: {
                  value: categoryId
                },
              }, callback);

**Comment by mcohen01** [comment]
dot notation for nested properties, though you may have to use the array form in this case:

```
qbo.findItems([
  {field: 'Name', value: name},
  {field: 'ParentRef.value', value: categoryId}
], callback);
```

**Comment by bsbechtel** [comment]
After I posted this, I figured out that placing the nested property in the top level appears to work as well.
