### ISSUE TITLE
getPreferences documentation

### ISSUE THREAD

**Issue by bsbechtel** [mcohen01/node-quickbooks#36]
In order to request preferences on a given company, you need to submit a blank object ("") instead of the company/realm ID, as the realm ID is already submitted in the API call. It is not obvious per the docs on how to modify the method call appropriately. You might want to update your docs (or add an example):

#### getPreferences(id, callback)
Retrieves the Preferences from QuickBooks

Arguments
    id - The Id of persistent Preferences // Add "" here
    callback - Callback function which is called with any error and the persistent Preferences

**Comment by mcohen01** [comment]
fix in 2.0.2. Thank you!
