### ISSUE TITLE
Queries on Boolean fields don't work

### ISSUE THREAD

**Issue by Paul-Martin** [mcohen01/node-quickbooks#37]
The following does not work:

```
qbo.findCustomer({ Active : true, limit : 1000})
```
or
```
qbo.findCustomer([
   { field : 'Active', value : true, operator : '=' }, 
   { field : 'limit', value : 1000 }])
```
Both cases result in the following error:

{ Fault: 
   { Error: 
      [ { Message: 'An application error has occurred while processing your request',
          Detail: 'System Failure Error: java.lang.String cannot be cast to java.lang.Boolean',
          code: '10000' } ],
     type: 'SystemFault' },
  time: '2016-01-15T11:02:23.728-08:00' }

Examining the generated url it is clear to see that the issue is that true is being quoted.
```
https://sandbox-quickbooks.api.intuit.com/v3/company/123145670668917/query?query=select * from customer where Active = 'true' startposition 1 maxresults 1000&minorversion=4
```

**Comment by mcohen01** [comment]
Should be fixed in 2.0.3
