### ISSUE TITLE
Including RequestID in API Call

### ISSUE THREAD

**Issue by bsbechtel** [mcohen01/node-quickbooks#38]
While researching how to handle API call failures, I came across this post about an update to the Quickbooks API. I thought it might be worth sharing if you weren't aware of it. Is it possible to add RequestID's to current requests just by adding the key to each request object?

https://developer.intuit.com/blog/2015/04/06/15346

**Comment by mcohen01** [comment]
Unfortunately I don't think this actually works as advertised. You can try it for yourself, just pass 1 as the request id for consecutive posts.

**Comment by bsbechtel** [comment]
I am not at all surprised. I'll play around with it a little later today. If I figure anything out, I will pass along what I learned.
