### ISSUE TITLE
Amount on debits not equal to credits

### ISSUE THREAD

**Issue by brandonros** [mcohen01/node-quickbooks#40]
This is more of a general accounting question so I highly apologize if this is the wrong place to ask it. I just can't think of a better support forum at the moment.

Can somebody please check this logic?

Goods on hand should *debit* the Inventory account.
Sales could *credit* the Sales account.
Purchases should *credit* the Purchases account.
Cost of good sold should *debit* the Supplies account.

I don't understand how the system (and I'm aware this is accounting 101, so I'm absolutely missing something trivial here) is expecting everything to be zero sum here.

Why would purchasing ever be equal to sales?

Any advice is highly appreciated!

**Comment by mcohen01** [comment]
Sorry, this is beyond the scope of this library. I would recommend working looking through some of the online product [documentation](http://quickbooks.intuit.com/tutorials/all-quickbooks-tutorials/).
