### ISSUE TITLE
Removal of Payments API

### ISSUE THREAD

**Issue by wmcbain** [mcohen01/node-quickbooks#42]
Hey there,

Saw in this commit [cd8226d3dc59d746ac88383419ebb90d6102c818](https://github.com/mcohen01/node-quickbooks/commit/cd8226d3dc59d746ac88383419ebb90d6102c818), that you removed functionality related to the payments flow. Wondering what the reason for that was, as I need this functionality in my app. I can always just amend the Quickbooks prototype locally, but wanted to make sure there wasn't other issues at play that I may be aware of that warranted it's removal.

Great work, and thanks for your help.

**Comment by mcohen01** [comment]
The Payments related bits were out of date, and have moved to https://github.com/mcohen01/quickbooks 

Unfortunately, the newer stuff is alpha quality at best. YMMV, but PRs welcome!

**Comment by wmcbain** [comment]
Ah great thanks!
