### ISSUE TITLE
Void a SalesReceipt

### ISSUE THREAD

**Issue by dhritzkiv** [mcohen01/node-quickbooks#43]
Is voiding a Sales Receipt currently possible?

[In the docs](https://developer.intuit.com/docs/api/accounting/salesreceipt), voiding a sales receipt is achieved by sending an update request, with `include=void` as part of the query string (weird, seeing as how the request is a POST request with a body, but _whatever_).

I attempted to pass in `include = "void"` in the request body, but that isn't allowed.

**Comment by mcohen01** [comment]
You should be able to void a SalesReceipt in 2.0.5 with something like:

```
qbo.updateSalesReceipt({
      Id: '50',
      SyncToken: '0',
      void: true
    }, function(err, data) {
      util.inspect(data, {showHidden: false, depth: null})
    })
```

**Comment by dhritzkiv** [comment]
Great! Thanks for the release.

**Comment by ShrihariMohan** [comment]
Need to update the documentation for this. But this works. I will raise a PR for doc update.
