### ISSUE TITLE
Using like operator for queries has issues

### ISSUE THREAD

**Issue by Emperoni** [mcohen01/node-quickbooks#46]
In order to use like with % such as '%prepaid inventory' I have had to pass it as '%25prepaid inventory' and on line 1925 of index.js I've had to comment out:
url.replace(/%/g, '%25')

this section only changes the first occurrence anyway, so it is ineffective at replacing all characters. 

I am using the like operator as follows:

accountsQuery = '%25Prepaid Inventory'
qbo.findAccounts([{field: 'Name', value: accountsQuery, operator: 'LIKE'}], function(err, account)

**Comment by mcohen01** [comment]
```javascript
qbo.findAccounts([
  {
    field: 'Name',
    value: '%Prepaid Inventory',
    operator: 'LIKE'
  }
], function(e, data) {
  console.log(JSON.stringify(data, null,2))
  done()
})
```

doesn't give me any errors.

Regarding L1925 of index.js, `url = url.replace(/%/g, '%25')` will *greedily replace all % characters in the string with %25. 

Sorry, I'm not sure what problem you're running into here.

**Comment by Emperoni** [comment]
Thank you so much for the reply. Let me explain my issue. 
If I submit '%Prepaid Inventory%' (with two % signs) the API somehow replaces characters and submits:
uri: 'https://quickbooks.api.intuit.com/v3/company/409491146/query?query=select%2520*%2520from%2520account%2520where%2520Name%2520LIKE%2520%2527%2525Prepaid%2520Inventory%25%2527',
which is obviously messed up and returns:
Message: 'Error parsing query',
          Detail: 'QueryParserError: Invalid content. Lexical error at line 1, column 7.  Encountered: "%" (37), after : ""',

what happened above, among other things, is that each space is replaced with %20, and then %20 is replaced with %2520.

I don't think that this is your code doing it. Does this mean that I cannot submit a LIKE with two % signs?

Thanks!

**Comment by mcohen01** [comment]
I would delete node_modules/node-quickbooks and then `npm install node-quickbooks --save` again and see what you get

**Comment by Emperoni** [comment]
Thank you for your time! That did it. My bad, I should have updated first.
