### ISSUE TITLE
Example for creating a File Attachable?

### ISSUE THREAD

**Issue by makeitrein** [mcohen01/node-quickbooks#49]
Hey devs,

I've successfully created a few invoices with node-quickbooks and now would like to upload some associated PDFs to each invoice. I believe that the **createAttachable** method is what I need to use, but I'm not quite sure how to include my PDF file into the payload. 

It looks like it's definitely possible with the [base Intuit API]( https://developer.intuit.com/docs/api/accounting/Attachable), but I'm not quite sure how to do it with node-quickbooks.

Metta,
J

**Comment by mcohen01** [comment]
With 2.0.7 you should be able to upload with something like:

```javascript
qbo.upload(
  fs.createReadStream('image.jpg'),
  'Invoice',
  '40',
  function(err, data) {
    console.log(err)
    console.log(data)
  done()
})
```

**Comment by makeitrein** [comment]
You, the Dude, are the man!

Thx for speedy response, will test tomorrow and report back.

**Comment by makeitrein** [comment]
Seems like things are working perfectly on my end - thx again.
