### ISSUE TITLE
Filtering Items By Type

### ISSUE THREAD

**Issue by nlk10010** [mcohen01/node-quickbooks#50]
I've tried everything I can think of but when I try to query Items by Type node keeps crashing. The filter object is contained in the following snippet:
`qbo.findItems([{field:'Active',value : true},{field:'fetchAll',value : true},
    {field : 'Type',value:'Service'}],function(_, items) {
      items.QueryResponse.Item.forEach(function(item) {
        //console.log(customer.Name)
      })
`
The Intuit Docs indicate that Items are filterable by Type and I make other filtered queries (e.g. Account by AccountType) that work fine. My assumption is that this is pilot error but just in case I thought I'd post; if it's NOT me then fine, otherwise perhaps someone can offer an idea of what I'm doing wrong.

Thanks.

**Comment by mcohen01** [comment]
That code looks fine. Can you post the error?

**Comment by nlk10010** [comment]
I will do what I can. I'm actually calling the function below from within an Alpha Anywhere program, using its facility to execute node services. I know, this adds a layer of ????? to the issue, but other queries work fine; e.g. as I said, Account queries filtered by AccountType. It's just that when this particular code is called Alpha crashes, I'm presuming it's node but maybe I'm painting things with too broad a brush.

`exports.handler = function(packet,response,sendResponse) {
    var consumerKey    = 'x',
    consumerSecret = 'y',
    oauth_token = 'z',
    oauth_token_secret = 'a',
    oauth_realmId = 'b'

	var QuickBooks = require('C:\\users\\norman kleinberg\\documents\\node_modules\\node-quickbooks');
    var  qbo = new QuickBooks(consumerKey,
                         consumerSecret,
                         oauth_token,
                         oauth_token_secret,
                         oauth_realmId,
                         true, // use the Sandbox
                         true); // turn debugging on

    qbo.findItems([{field:'Active',value : true},{field:'fetchAll',value : true},
    {field : 'Type',value:'Service'}],function(_, items) {
      items.QueryResponse.Item.forEach(function(item) {
        //console.log(customer.Name)
      })
      response.data = items;
      sendResponse(response);
    })
}`

As long as you're telling me that the filter looks OK I am going to see if I can debug from within Alpha to get an error object back. If I do then I'll post it.

Thanks much for the prompt response, didn't expect it. Your code is the ONLY way I've found so far to get to QBO from within Alpha. I currently have an App on Appcenter but it's in C#/DevExpress and I'd like to migrate to Alpha if possible (for reasons we don't need to go into).

**Comment by nlk10010** [comment]
OK, the attached contains the output I got when I tried to run the module interactively from within Alpha (authorization details removed). It MIGHT give you some clue (then again, it might be meaningless :) ).

Thanks for any pointers.

[ItemQueryErrors.txt](https://github.com/mcohen01/node-quickbooks/files/191188/ItemQueryErrors.txt)

**Comment by mcohen01** [comment]
You're not getting any results back that match your query:

```javascript
qbo.findItems([
    {field:'Active', value : true},
    {field:'fetchAll', value : true},
    {field : 'Type', value: 'Service'}
], function(_, items) {
  console.log(JSON.stringify(items, null, 2))
  done()
})
```

**Comment by nlk10010** [comment]
Stipulating to the fact that you know much more about this than I do (or probably ever will), that is puzzling. I say that because if I remove the filter on "Type" then I get a perfectly fine response with a bunch of items, many of which are of "Type" "Service". I know this because I filter them in my code, on the client side, and display them in a dropdown. So there ARE plenty of service items in my Sandbox. I tried using your code above and the console window simply displayed the same error response I pasted into my file attachment. 

Maybe it IS something I'm doing or maybe it's at Intuit's end or MAYBE it's in your code, I don't know, but at this point I'll just filter things on the client (there aren't many items in the first place). If someone reading this thread has successfully used findItems with a filter on Type then I'd LOVE to know about it (also how you check for a null response).

Again, thanks for responding.

**Comment by mcohen01** [comment]
In the console output you included, the debugging shows no results from the query:
```
{ QueryResponse: {}, time: '2016-03-27T16:07:35.578-07:00' }
```
And the error at the top of the stacktrace:
```
Unhandled rejection TypeError: Cannot read property 'Item' of undefined
```
which is raised from your code at:
```javascript
function(_, items) {
  items.QueryResponse.Item.forEach(function(
```

The typical pattern is to check for errors and also for a non-null response:
```javascript
function(err, items) {
  if (err) console.log(err)
  else if (items.QueryResponse.Item) {
    console.log(items.QueryResponse.Item)
  } else console.log('no results')
}  
```

**Comment by nlk10010** [comment]
OK. The lack of error-checking is my sloppiness/laziness, I was just trying to get this "to work" from within Alpha. I didn't interpret the error as a null response.

To the larger question, the only possible explanation for this (IMO) is a problem at Intuit's end with SELECT queries of Items with Type in a Where clause. I've run into similar problems with Accounts when working in C#, this may or may not be another case. Regardless, I'll see if I can run the SELECT manually (Intuit used to let you do this on their site) and I will post my issue on their Developer board, perhaps they have a suggestion.

Thanks again for your help.

**Comment by corey-mc** [comment]
I'm also having trouble filtering Items by Type: 
`qbo.findItems([{ field: 'Active', value: true }, { field: 'Type', value: 'Inventory' }],`...
If I remove the 'Type' filter I get results for only the active records as expected. @nlk10010 Did you find a solution or workaround for this?  Thanks!

**Comment by nlk10010** [comment]
Corey:

No, I didn't, unfortunately. I can filter accounts by Type but not items.
For items I simply use:

    qbo.findItems([{field:'Active',value : true},{field:'fetchAll',value :
true}],function(err, items) { ............

and filter on the client.


Norman

On Tue, May 24, 2016 at 3:20 PM, Corey McSparen <notifications@github.com>
wrote:

> I'm also having trouble filtering Items by Type:
> qbo.findItems([{ field: 'Active', value: true }, { field: 'Type', value:
> 'Inventory' }],...
> If I remove the 'Type' filter I get results for only the active records as
> expected. @nlk10010 <https://github.com/nlk10010> Did you find a solution
> or workaround for this? Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mcohen01/node-quickbooks/issues/50#issuecomment-221369719>
>



-- 
Norman L. Kleinberg
Technical Representative
*BusinessTECH Consulting Inc.*
(212) 564-3909 (V)
(516) 423-9191 (Direct)
nlk@btechinc.net
www.btech.bz

**Comment by corey-mc** [comment]
I am also post-processing the results on the Node side to filter by Type as a workaround. Thanks for the quick response.

**Comment by mcohen01** [comment]
@corey-mc  Your code works fine for me. 

```
qbo.findItems([
      { field: 'Active', value: true },
      { field: 'Type', value: 'Inventory' }
    ], (err, data) => {
      console.log(err)
      console.log(JSON.stringify(data, null, 2))
      
    })
```
Are you getting an error? Can you post the json you get back when filtering `Inventory` and when not?

**Comment by corey-mc** [comment]
I'm not getting an error, just an empty result.  

Response with the Type filtering:
``{
  "QueryResponse": {},
  "time": "2016-05-24T14:17:04.894-07:00"
}``

Here is the generated query (company Id has been fudged)
``invoking endpoint: https://sandbox-quickbooks.api.intuit.com/v3/company/1/query?query=select * from item where Active %3D true and Type %3D %27Inventory%27 startposition 1 maxresults 1000``

Response without the Type filter:
``
{
  "QueryResponse": {
    "Item": [
      {
        "Name": "Concrete",
        "Description": "Concrete for fountain installation",
        "Active": true,
        "FullyQualifiedName": "Concrete",
        "Taxable": true,
        "UnitPrice": 0,
        "Type": "Service",
        "IncomeAccountRef": {
          "value": "48",
          "name": "Landscaping Services:Job Materials:Fountains and Garden Lighting"
        },
        "PurchaseCost": 0,
        "TrackQtyOnHand": false,
        "domain": "QBO",
        "sparse": false,
        "Id": "3",
        "SyncToken": "1",
        "MetaData": {
          "CreateTime": "2016-04-10T10:36:03-07:00",
          "LastUpdatedTime": "2016-04-13T12:47:47-07:00"
        }
      },
      {
        "Name": "Design",
        "Description": "Custom Design",
        "Active": true,
        "FullyQualifiedName": "Design",
        "Taxable": false,
        "UnitPrice": 75,
        "Type": "Service",
        "IncomeAccountRef": {
          "value": "82",
          "name": "Design income"
        },
        "PurchaseCost": 0,
        "TrackQtyOnHand": false,
        "domain": "QBO",
        "sparse": false,
        "Id": "4",
        "SyncToken": "0",
        "MetaData": {
          "CreateTime": "2016-04-10T10:41:38-07:00",
          "LastUpdatedTime": "2016-04-10T10:41:38-07:00"
        }
      },
....``

Here is the generated query:
``https://sandbox-quickbooks.api.intuit.com/v3/company/1/query?query=select * from item where Active %3D true startposition 1 maxresults 1000``

I also had trouble (same empty result set) with the Type = Inventory filter when entering the query directly in the QBO API Explorer for my sandbox company:
``select * from item where Active = true and Type = 'Inventory' startposition 1 maxresults 1000``

**Comment by mcohen01** [comment]
Let me ask a dumb question, when you don't filter by type, will actually get results back that have Type = Inventory?

**Comment by corey-mc** [comment]
Yep :)

**Comment by mcohen01** [comment]
>I also had trouble (same empty result set) with the Type = Inventory filter when entering the query directly in the QBO API Explorer for my sandbox company:
select * from item where Active = true and Type = 'Inventory' startposition 1 maxresults 1000

Yeah, I'm gonna say you should file a ticket with Intuit for this one. The actual debug query you posted is the same one I see when I run it and it filters fine for me. Only other thing I can think of is somehow this is sandbox specific, but that is probably just a wild shot in the dark that will prove inaccurate. It looks to be some kind of backend issue. Good luck.
