### ISSUE TITLE
Preferences Spelling?

### ISSUE THREAD

**Issue by sbr464** [mcohen01/node-quickbooks#51]
I was getting an error with the "FindPreferenceses" Method,

Quickbooks has this spelled as "Preferences" (extra 'es' on end of your method). Could this be an issue?

Thanks

https://developer.intuit.com/docs/api/accounting/preferences

**Comment by mcohen01** [comment]
Extra 'es' is due to code generation. I'm sure that's not your issue though (that method works fine). Can you post your code with debugging turned on?

**Comment by sbr464** [comment]
Yeah, apologies for not being clear. There isn't an issue with your library. 

I'm doing the same thing, with code generation on my side, I have the singular and plural names stored in a collection, and I map over the endpoints from quickbooks to pull down the entire api/company file at one time. There are just inconsistencies with about 5 I believe endpoints where the return is different than the endpoint name which your library uses. 

although it would be nice if it just matched, It's no biggie. I will create a third column in my collection that stores the endpoint name you specifically use. We are just defining a schema because we dynamically create the collections in mongo and also pull from the API from this endpoint list. 
```
// small example of code using dynamic lookups to iterate over and download data 


      endpointArray = QB_Endpoints.find().fetch();

    _.each(endpointArray, function(endpoint) {
      var collection = endpoint.name;
      var response = Async.runSync(function(done) {
        qbo['find' + endpoint.namePlural]({
          fetchAll: true
        }, function(err, res) {
          if (err) {

// summarized
done(null, res.QueryResponse[endpoint.name]);

//  another dynamic reference etc..

  global['QB_' + collection].insert(doc, function(err, id) {

```
