### ISSUE TITLE
oauth_problem: 'signature_invalid'

### ISSUE THREAD

**Issue by CalebEverett** [mcohen01/node-quickbooks#54]
Hi, thank for putting this library together. I think I've followed the getting started instructions, gotten the secret and key entered correctly, but am getting this signature invalid error. Can you see where I might have gone wrong?

    "statusCode": 401,
    "body": "oauth_problem=signature_invalid",
    "headers": {
        "date": "Tue, 05 Apr 2016 17:27:54 GMT",
        "server": "Apache",
        "www-authenticate": "OAuth oauth_problem=\"signature_invalid\"",
        "cache-control": "no-cache, no-store",
        "pragma": "no-cache",
        "content-length": "31",
        "connection": "close",
        "content-type": "text/plain",
        "x-pad": "avoid browser bug"
    },
    "request": {
        "uri": {
            "protocol": "https:",
            "slashes": true,
            "auth": null,
            "host": "oauth.intuit.com",
            "port": 443,
            "hostname": "oauth.intuit.com",
            "hash": null,
            "search": null,
            "query": null,
            "pathname": "/oauth/v1/get_request_token",
            "path": "/oauth/v1/get_request_token",
            "href": "https://oauth.intuit.com/oauth/v1/get_request_token"
        },
        "method": "POST",
        "headers": {
            "Authorization": "OAuth oauth_callback=\"http%3A%2F%2Flocalhost%3A3000%2Fcallback%2F\",oauth_consumer_key=\"qyprdowSUdCZUHEuLT7ferE56I940i\",oauth_nonce=\"9cb04e59470c4d84b853aadebfbf1052\",oauth_signature_method=\"HMAC-SHA1\",oauth_timestamp=\"1459877274\",oauth_version=\"1.0\",oauth_signature=\"tOqGLEMnqo3h0vLWiGWAucHbJYg%3D\"",
            "content-length": 0
        }
    }
`
https://developer.intuit.com/hub/blog/2015/02/19/oauth-for-intuit-demystified
http://oauthbible.com/
http://stackoverflow.com/questions/19358388/how-properly-create-oauth-signature-base-string

**Comment by mcohen01** [comment]
Are you running the example app? Did you paste your consumerKey and consumerSecret into app.js from the developer console?

**Comment by CalebEverett** [comment]
Thanks for the quick reply, I hadn't pasted the secret correctly.

**Comment by mcohen01** [comment]
Heh. It would be interesting to see some metrics across sites on the percentage of users who actually click these "copy to clipboard" buttons, like on github as well, with the clone url. I know half the time I don't use them either, for some unexplained reason.

**Comment by mcohen01** [comment]
I looked at the html on Intuit's site and didn't see anything obvious that would cause a double click in an input field to break like that. Maybe angular? No idea....

**Comment by tristansokol** [comment]
depending on browser there can be an issue where you end up selecting more than just the key/secret with a double click. In the screenshot below I had just double clicked my consumer key and the word 'key' is also selected. I'll see if I can get some stats about the 'copy to clipboard' button usage. 
<img width="750" alt="screen shot 2016-04-05 at 4 04 27 pm" src="https://cloud.githubusercontent.com/assets/867661/14300868/28c91096-fb48-11e5-9d2b-56b11ef41e2f.png">
