### ISSUE TITLE
XML response for authentication Failed. 

### ISSUE THREAD

**Issue by nejizofa** [mcohen01/node-quickbooks#57]
Hello,

First thanks a lot for a great module. It is working great for most of my use cases. 

However I have one issue where when a user token expires and Quickbooks responds with an authorization failed. The module passes back XML error code instead of JSON like the rest of the module.

I am not sure if I have missed a configuration setting or something. 

Strange that only the authorization failed returns xml and everything else returns JSON. 

Error: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse time="2016-05-16T10:43:19.951-07:00" xmlns="http://schema.intuit.com/finance/v3">
    <Fault type="AUTHENTICATION">
        <Error code="3200">
            <Message>message=ApplicationAuthenticationFailed; errorCode=003200; statusCode=401</Message>
            <Detail>SignatureBaseString: GET&amp;https%3A%2F%2Fsandbox-quickbooks.api.intuit.com%2Fv3%2Fcompany%2F$$$%2Fquery&amp;minorversion%3D4%26oauth_consumer_key%xxx%26oauth_nonce%xxx%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1463420599%26oauth_token%3xxx%26oauth_version%3D1.0%26query%3Dselect%2520%252A%2520from%2520invoice%2520orderby%2520Balance%2520desc%2520startposition%25201%2520maxresults%25203</Detail>
        </Error>
    </Fault>
</IntuitResponse>

**Comment by mcohen01** [comment]
This is down to the way the server api handles certain kinds of errors. Even though you requested json with an `Accepts` header, the error is not "deep enough" in the server stack to return json to you. Basically you have to manually check for xml. (This client [does](https://github.com/mcohen01/node-quickbooks/blob/master/index.js#L1978) as well.)

**Comment by nejizofa** [comment]
Thank you for your quick response. I have modified my application to handle this scenario.

**Comment by nitin7dc** [comment]
any updates on this ? getting XML in error response.
