### ISSUE TITLE
method missing: findCustomers

### ISSUE THREAD

**Issue by araskin** [mcohen01/node-quickbooks#61]
Hi,

I have instantiated the object and it seems to be missing the findCustomers method which is documented. Am I instantiating it incorrectly?

http://screencast.com/t/8PRXiH1R8MqJ

**Comment by mcohen01** [comment]
Whatever you're dumping that to is not showing you everything. It's there.

**Comment by araskin** [comment]
Turns out I had the wrong node module installed (node-quickbooks versus quickbooks). Anyway all good now. Now I am getting some weird auth error but I will deal with that separately. Thanks for your response.
