### ISSUE TITLE
Use of "fetchAll" is breaking other query parameters.

### ISSUE THREAD

**Issue by SteveShantz** [mcohen01/node-quickbooks#62]
When I initially wrote my code I did not use "fetchAll". There is the possibility that our requests could exceed the limit of 1000 records. So I would like to make use of the “fetchAll” parameter.

Before making changes to use “fetchAll”, here is a snippet of our code used to get a Trial Balance report:

```
// Put the dates in the required format YYYY-MM-DD.
newStart = newStart.format('YYYY-MM-DD');
newEnd   = newEnd.format('YYYY-MM-DD');

// Get the trial balance for the required time period.
var query = {
    start_date: newStart,
    end_date:  newEnd
};
qbo.reportTrialBalance(query, function(err, theTrialBalance) {
    .
    .
    .
});
```

The above code is working and retrieves the trial balance report for the specified time period. 

I’m not sure how the “fetchAll” parameter should be added. We’ve tried the following ways of creating the query object, but they have not worked:

```
var query = [
   {field: ‘fetchAll’, value: true},
   {field: ‘start_date’, value: newStart},
   {field: ‘end_date’, value: newEnd}
];

var query = [
   {fetchAll: true},
   {start_date: newStart},
   {end_date: newEnd}
];

var query = [
   {field: ‘fetchAll’, value: true},
   {‘start_date’: newStart},
   {‘end_date’: newEnd}
];
```

In each case, a trial balance is returned. But the data returned is for ‘this month-to-date’ and not for the date range specified by ‘start_date’ and ‘end_date’. Also wanting to use "fetchAll" with the following and experiencing similar issues:
- qbo.reportBalanceSheet()
- qbo.findAccounts()
- qbo.reportProfitAndLoss()
- qbo.reportGeneralLedgerDetail()
- qbo.reportBalanceSheet()

Can you tell me the correct way to use “fetchAll” together with being able to set the start and end dates?

**Comment by mcohen01** [comment]
If you set the debug flag when you create the QuickBooks object you'll see in the console the actual queries that are generated.  That should give you more of a hint.

**Comment by SteveShantz** [comment]
Set the debug flag. For

```
var query = [
   {field: ‘fetchAll’, value: true},
   {field: ‘start_date’, value: newStart},
   {field: ‘end_date’, value: newEnd}
];
```

This is the query that was generated:
```
{ request: 
   { uri: 'https://sandbox-quickbooks.api.intuit.com/v3/company/123145760145392/reports/TrialBalance?0=%5Bobject%20Object%5D&1=%5Bobject%20Object%5D&2=%5Bobject%20Object%5D&minorversion=4',
     method: 'GET',
     headers: 
      { 'User-Agent': 'node-quickbooks: version 2.0.8',
        'Request-Id': '3be56ed0-6b01-11e6-ac90-77b767935eaf',
        host: 'sandbox-quickbooks.api.intuit.com',
        accept: 'application/json',
        Authorization: 'OAuth oauth_consumer_key="qyprd3CxXhaOrqFiiZDOx9VJEAGTrK",oauth_nonce="2dce5739808b4b49be16957a3873741b",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1472156372",oauth_token="qyprd3bWMUwPlEfLSpuQOnZHLx4ySveMwjTAa8aVtOiCELhH",oauth_version="1.0",oauth_signature="sAZLGHaSY9sC4USEfJgsmcMRjfE%3D"' } } }
```

This part of the query doesn't seem right:

TrialBalance?**_0=%5Bobject%20Object%5D&1=%5Bobject%20Object%5D&2=%5Bobject%20Object%5D_**&minorversion=4

**Comment by mcohen01** [comment]
The `report` functions take an optional map that simply gets translated to query params, so for example, the trial balance report would be retrieved with something like:

```javascript
qbo.reportTrialBalance({
    start_date: newStart,
    end_date: newEnd
}, function(err, data) {
  console.log(JSON.stringify(data, null, 2));      
})
```

Only the finder functions accept the "array of criteria" style args:

```javascript
qbo.findAccounts([
  {field: 'fetchAll', value: true},
  {field: 'Metadata.CreateTime', value: '2015-12-31', operator: '>'}
], function(err, data) {
  console.log(JSON.stringify(data, null, 2));  
})
```

**Comment by SteveShantz** [comment]
So that means that finder functions can use "fetchAll", but report function cannot.

**Comment by mcohen01** [comment]
>So that means that finder functions can use "fetchAll", but report function cannot.

Right, the report functions do not return many rows.
