### ISSUE TITLE
Get Invoice PDF Without Buffering

### ISSUE THREAD

**Issue by bendytree** [mcohen01/node-quickbooks#63]
I think I know the answer - but just wanted to check.

Is there any way to get an invoice PDF without buffering it into memory? Ideally I'd like to stream it to the client if possible.

It looks like [getInvoicePdf](https://github.com/mcohen01/node-quickbooks#getInvoicePdf) uses request to buffer the entire response in memory before calling back.

**Comment by mcohen01** [comment]
You could probably add an optional file param to `getInvoicePdf` and have request [stream](https://github.com/request/request#streaming) it to a file, then stream that to the client. But this library has no notion of the http request/response from the client's perspective (i.e. when used in the context of a webapp), nor should it imo. Is your invoice too large to fit in memory?

**Comment by bendytree** [comment]
I just generally avoid buffering a large binary like this if possible.

I think it's fairly standard to return a stream if the callback is omitted. I'm pretty sure that's how [request](https://github.com/request/request#streaming) works. So `node-quickbooks` could [return the response stream here](https://github.com/mcohen01/node-quickbooks/blob/master/index.js#L1979). If the callback was omitted then I think request would stream it.

It'd be a big change though since [every endpoint](https://github.com/mcohen01/node-quickbooks/blob/master/index.js#L578) would need to return the `module.request` call. Plus, `module.unwrap` is called everywhere and it returns a noop if the callback was omitted.
