### ISSUE TITLE
OAuth 2.0 support

### ISSUE THREAD

**Issue by unsaltedMixedNuts** [mcohen01/node-quickbooks#77]
Hi.

Does this `node-quickbooks` package support OAuth 2.0?  I am newly using the QuickBooks API and have only recently set up my QB developer account after the July 17, 2017 cutoff, which means I have no choice but to use OAuth 2.0.

Here's the original information from the QuickBooks API Docs:
```
If your developer account has created apps before July 17, 2017, any apps created by that account, including future apps and apps under development now, will use OAuth 1.0a. There is no requirement to migrate OAuth 1.0a apps to OAuth 2.0. 

If your developer account has not created any apps until after July 17, 2017, all apps created by that account will use OAuth 2.0. 

Intuit Developer Group are working on providing a path to migrate OAuth 1.0a keys from OAuth 1.0a to OAuth 2.0, and to enable all developer accounts to create new apps that use OAuth 2.0. We will notify the community once this path is ready.

The information below helps you to identify which OAuth stack your apps are using.
```

**Comment by mcohen01** [comment]
Hi Mel, unfortunately this library hasn't been updated to support OAuth 2. I looked very briefly at the [Intuit docs](https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app) and it didn't look like the task was too onerous. PR's welcome :)  The [example app](https://github.com/mcohen01/node-quickbooks/tree/master/example) might help jump start someone who was interested in contributing this....

**Comment by unsaltedMixedNuts** [comment]
OK.  I figured as much but wanted to double check. Thanks for the quick reply!

**Comment by mcohen01** [comment]
I think this should be fixed by https://github.com/mcohen01/node-quickbooks/pull/79
@unsaltedMixedNuts
