### ISSUE TITLE
No PnL accounts coming across on GeneralLedger report /w directly specifying account_type

### ISSUE THREAD

**Issue by jasonHooten** [mcohen01/node-quickbooks#82]
After playing around with the GL report I've noticed that if I don't specify an account_type, then the report returns with no PnL accounts? 

Then I noticed your build message...

## these are broken on QBO right now
**GeneralLedgerDetail**
DepartmentSales
ClassSales

https://github.com/mcohen01/node-quickbooks/blob/master/build/report.txt

and was wondering if there was a correlation or if the QBO api was broken.

**Comment by mcohen01** [comment]
That message dates from a long time ago. I have no idea if it's still true today.
