### ISSUE TITLE
Can't connect to both Sandbox and Live Endpoints

### ISSUE THREAD

**Issue by toddgeist** [mcohen01/node-quickbooks#9]
It's not possible to build an app that can connect to the Sandbox and the Production endpoints.  You can only do one or other. This is becuase all instances share the same endpoint variables.

I took a look at fixing this but it doesn't look like the request that gets made doesn't know much about the instance other then the props for authentication.  I didn't see an easy way to make it work.

If you have time to point me in the right direction I'll see if I can figure it out.

**Comment by mcohen01** [comment]
v1.0.14 should work for you

**Comment by toddgeist** [comment]
yup that did it.  Thanks!
