### ISSUE TITLE
Any plans for TLS 1.2?

### ISSUE THREAD

**Issue by jasonHooten** [mcohen01/node-quickbooks#91]
Deadline is Dec 31 this year, will you be updating the sdk before then?

**Comment by mcohen01** [comment]
What needs to be updated?

**Comment by jasonHooten** [comment]
I'll put a pull request in for it, thanks

**Comment by tonypatton** [comment]
Any update here?

**Comment by dgreuel** [comment]
Received notice that apps will break tomorrow if not upgraded to TLS 1.2.
@jasonHooten, it looks like you made the changes on your fork, but forgot to create the pull request?
[01065f9](https://github.com/jasonHooten/node-quickbooks/commit/01065f97494c55c837533da89ab5c462a7518101)

**Comment by triemstr** [comment]
@jasonHooten @dgreuel Any update to this? Can we make the pull request if needed?

**Comment by jasonHooten** [comment]
I ended up not having to do anything to support TLS 1.2, closing the ticket.
