### ISSUE TITLE
OAuth2 Not refreshing oauthtoken

### ISSUE THREAD

**Issue by CheeJustin** [mcohen01/node-quickbooks#92]
I'm using `node-quickbooks` OAuth2 to maintain a session, but when the oauthtoken expires, it doesn't automatically refresh the token. I'll get the error below:

```
[ { message: 'message=AuthenticationFailed; errorCode=003200; statusCode=401',
  detail: '',
  code: '3200',
  element: null } ]
```

Is this expected behaviour? If so is there a purpose in initializing the QuickBooks object with the refresh token?

**Comment by jamesrusso** [comment]
I saw this as well. The refresh token is passed in, but never used.

**Comment by jamesrusso** [comment]
Latest version on NPM introduces a refreshToken method.  +1 to close this issue.
