### ISSUE TITLE
OAuth2 example not working?

### ISSUE THREAD

**Issue by jamesrusso** [mcohen01/node-quickbooks#95]
After placing my app's id and secret into the app.js example and running it. I get the following screen and results in console. 

![image](https://user-images.githubusercontent.com/682807/35626200-f3abe73a-0662-11e8-9876-963a0cd8ab87.png)

Express server listening on port 3000
{ oauth_problem: 'parameter_rejected',
  oauth_parameters_rejected: 'oauth_consumer_key' }

**Comment by jamesrusso** [comment]
Sorry. I was using the wrong example folder!

**Comment by Sam-Gram** [comment]
Did you put the id as the key and the secret as the secret? @jamesrusso
